### ISSUE TITLE
Runtime Error while running the training script

### ISSUE THREAD

**Issue by krishnachaitanya7** [BestJuly/IIC#4]
I am trying to the training script like this:
```python
python train_ssl.py --dataset=ucf101
```
```
{'print_freq': 10, 'tb_freq': 500, 'save_freq': 40, 'batch_size': 16, 'num_workers': 8, 'epochs': 240, 'learning_rate': 0.01, 'lr_decay_epochs': '120,160,200', 'lr_decay_rate': 0.1, 'beta1': 0.5, 'beta2': 0.999, 'weight_decay': 0.0001, 'momentum': 0.9, 'resume': '', 'model': 'r3d', 'softmax': True, 'nce_k': 1024, 'nce_t': 0.07, 'nce_m': 0.5, 'feat_dim': 512, 'dataset': 'ucf101', 'model_path': './ckpt/', 'tb_path': './logs/', 'debug': True, 'modality': 'res', 'intra_neg': True, 'neg': 'repeat', 'seed': 632, 'model_name': 'intraneg_r3d_res_1012', 'model_folder': './ckpt/intraneg_r3d_res_1012', 'tb_folder': './logs/intraneg_r3d_res_1012'}
[Warning] The training modalities are RGB and [res]
Use split1
v_LongJump_g18_c03 896] BT 5.066 (5.538)        DT 4.007 (4.468)        loss 15.277 (20.188))   1_p -0.001 (0.014)      2_p -0.009 (-0.007)


Traceback (most recent call last):
  File "train_ssl.py", line 341, in <module>
    main()
  File "train_ssl.py", line 308, in main
    criterion_1, criterion_2, optimizer, args)
  File "train_ssl.py", line 166, in train
    for idx, (inputs, u_inputs, v_inputs, _, index) in enumerate(train_loader):
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/krishna/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/tankpool/home/krishna/PycharmProjects/Inter-intra-video-contrastive-learning/datasets/ucf101.py", line 123, in __getitem__
    raise
RuntimeError: No active exception to reraise
```
It always gives me this runtime error. I followed all the steps in the README. Still unable to figure out. Can you please help me out? Thank you!

**Comment by krishnachaitanya7** [comment]
I think I figured out what the problem is. In the dataset, there is a folder called ```TSP_Flows``` inside ```v_LongJump_j18_c03``` folder inside the rgb_16 dataset downloaded from the pre-computed sources mentioned in the readme. The TSP_Flows folder has 10 files, which lead the code to believe that they are only 10 files/frames when the code expects a minimum of 16 frames inside each folder. The files inside the TSP_Flow are the .mat files, so they are unrelated to the dataset (I guess), so I deleted them. After deleting them, everything worked normally.
